name: cache

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix️"
        uses: cachix/install-nix-action@v15

      - name: "Install Cachix️"
        uses: cachix/cachix-action@v10
        with:
          name: typelevel
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: "Build dev shells"
        run: for shell in library application; do nix develop .#${shell} -c true; done
