name: cache

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Nix️"
        uses: cachix/install-nix-action@v30

      - name: "Install Cachix️"
        uses: cachix/cachix-action@v15
        with:
          name: typelevel
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: "Run checks"
        run: nix -L flake check
